version: '3.8'

services:
  dev:
    build: .
    environment:
      NODE_ENV: development
      RAPIDS_PASSWORD: ${RAPIDS_PASSWORD}
      RAPIDS_URLS: ${RAPIDS_URLS}
      RAPIDS_USERNAME: ${RAPIDS_USERNAME}
    networks:
      - services-network
    volumes:
      - ./:/app

networks:
  services-network:
    name: services-network
