version: '3.8'

services:
  ui:
    build: ./ui
    environment:
      NODE_ENV: development
      PORT: 8080
      VUE_APP_SOCKETS_URL: localhost:8081
    networks:
      - services-network
    ports:
      - 8080:8080
    volumes:
      - ./ui:/app

  sockets:
    build: ./sockets
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      NODE_ENV: development
      PORT: 8081
      RAPIDS_URLS: rapids:9092
    networks:
      - services-network
    ports:
      - 8081:8081
    volumes:
      - ./sockets:/app

networks:
  services-network:
    name: services-network
