version: '3.8'

services:
  sockets:
    build: ./sockets
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      NODE_ENV: development
    networks:
      - services-network
    volumes:
      - ./sockets:/app

networks:
  services-network:
    name: services-network
